# Generated by Django 3.2.12 on 2023-04-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anleitung',
            name='thumbnailbild',
            field=models.ImageField(default=None, upload_to='images/thumbnail'),
        ),
        migrations.AddField(
            model_name='anleitungsschritt',
            name='schrittbild',
            field=models.ImageField(default=None, upload_to='images/Schrittbilder/'),
        ),
        migrations.AddField(
            model_name='komponente',
            name='kompbild',
            field=models.ImageField(default=None, upload_to='images/Kompbilder'),
        ),
    ]
