# Generated by Django 3.2.12 on 2023-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0002_auto_20230422_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anleitung',
            name='thumbnailbild',
        ),
        migrations.AddField(
            model_name='anleitung',
            name='img',
            field=models.ImageField(default=None, upload_to='images/thumbnail'),
        ),
        migrations.AlterField(
            model_name='komponente',
            name='kompbild',
            field=models.ImageField(default=None, upload_to='images/Komponentenbilder'),
        ),
    ]
