# Generated by Django 3.2.12 on 2023-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0004_alter_anleitung_dauer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anleitung',
            name='dauer',
            field=models.DurationField(),
        ),
    ]
