# Generated by Django 3.2.12 on 2023-05-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0005_alter_anleitung_dauer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
