# Generated by Django 3.2.12 on 2023-05-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0006_alter_profil_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='passwort',
            new_name='password',
        ),
    ]
