# Generated by Django 3.2.12 on 2023-06-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SBSInstructions', '0010_auto_20230601_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profil',
        ),
    ]
