# Generated by Django 3.2.12 on 2023-06-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0014_auto_20230601_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='benutzername',
        ),
    ]
