# Generated by Django 3.2.12 on 2023-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0015_remove_profil_benutzername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='profil',
            name='benutzername',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
