# Generated by Django 3.2.12 on 2023-06-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0016_auto_20230601_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='benutzername',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='password',
        ),
    ]
