# Generated by Django 3.2.12 on 2023-06-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0018_profil_benutzername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='benutzername',
        ),
    ]
