# Generated by Django 3.2.12 on 2023-06-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0022_auto_20230605_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='benutzername',
        ),
    ]
