# Generated by Django 3.2.12 on 2023-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstructions', '0023_remove_profil_benutzername'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='benutzername',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
